notifications:
  email: false

language: go
go:
  - "1.11.x"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make check-style
  - make test

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: VZqD+8KhR7KW54AUu247jrC8tcj/1eOhW4ljl9/9eLe2EfSlNbtuy1kVP2RfWl+fJ5Cy+/aeP2oM4SoR6RkdFRN5c50IIiVKIJs98WiljzZ/PevaDod35yJscgP1TYrKBQhZjHTqNREGjn3QtmcBQH7y1ZgBeM7jDkij1+7gQta0psLh2+7mRpANvDAZJ2/EAyOA2gOYv9A5b4/dcXqSm85RdME6S6IjgdSWMOW1ZyqPVO8bhRZvorycs4NgW76xoNSwL+LSY86prmQz+jGeUZ5XUdMOC6SzjCASV11hIaN3tCiMm8mZ3WVi8eSwanCazmXBUoaU8Fdeh/tNndu1Qa1948UOP+5xOIe9jDLIO/8Fo7e/n9wqefUNx6mdyeaH6QJh9sfZ+QgaLfcznjSyL0C8leFH8GP+p2XKMVKBoTE5q6SNR0JdV1kPSAA7HasEpyvKYlbZIP1ZRFXh6xLHtwX5HYVr61bQeJfxHFZy+9n5zFCeImGW4WIX04mgU67udvSEgEgGrzOqGw8uTLh5zpwT82x3GV/QNHPgiLsCeQloqJW/yXyEUCTz1czJRCDGsmB9rhUEYcmeEULce9RWnR3OqH21WuOAuvuL//f/q9G9z71mVsg6wv3QbaFXq+enT4ZTYl4DRH6jsWTxpwEozd+VrWVC2FUWo6syBXNimjs=
  skip_cleanup: true
  file_glob: true
  file: "dist/statuspage-*.tar.gz"
  on:
    repo: cpanato/mattermost-plugin-statuspage
    tags: true
