notifications:
  email: false

language: go
go:
  - "1.11.x"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make check-style
  - make test

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: u3T7r62HHndGRtN5PpDPSVE6RwNG5ZTj0el2ZRUe8eey0JRXzDr6fQK6DkjV6Yk2z0QzEVhjGrrqZ3Qx9XfBelJYshBBH+4n1JDdhUsGp2iL8xNxHw/Wj0+FiEAaZ4idXDKSZIHkhdhBysHiLJ3HCv885iMcrAI4bW2yRlkFLIJMKoqmyG2Kx6s3WqUGczFMdNkRvN1i6ICzc7DPPe8stqMChfAH0wIIgcvtaajyF8cpZIbgRtsCgUECAFH0XnjcCWPxFayoLj3OYPkhxRtAZjhyBv3tJ2m121eQWt5/a1TarbDCLNu4tYBqMs4Ks8Jvrx0kRpEtM1IlsBVYWXzop4vixGCSJlsUKsOnL2XdnvonHM/Q8y8LdYpjP8i19+6Y/Rld91insE7IgTNqHamPSkPI/xGoyIjySLyGIzdxDa+KG0cdH/HDKk1xF8tkQMSheBd5Fd9KHyejoO9v9IAS6jmQrxk3bpzTF1ijbz5vL5y9GEbAHimS16n2GteG/Co6p9JPsFjJparoL4+K6l5dksYqz2mMgrLYOQcUC3jacNBA7NfiqivY2VeA8b4JErts6Ub0E7STVI8MA7atT2cLCoSXSp3eW9NY69aXYg+OV1dYThwasdu422DlcOfQ+Ku/gEtjTWXZiBHBvylzprf4dj7PTVuKLEb9fuGnJTqHouQ
  skip_cleanup: true
  file_glob: true
  file: "dist/statuspage-*.tar.gz"
  on:
    repo: cpanato/mattermost-plugin-statuspage
    tags: true
